from sqlalchemy.orm import Session
from schemas.notes import NoteCreate
from models.models import Note, Tag, User
from core.database import get_chroma
from ml.nlp import extract_tags
from ml.embeddings import create_embedding
import uuid
import asyncio


def _ensure_user(db: Session, user_uuid: uuid.UUID) -> User:
    existing_user = db.query(User).filter(User.id == user_uuid).first()
    if existing_user:
        return existing_user

    user = User(
        id=user_uuid,
        email=f"{user_uuid}@local.secondbrain"
    )
    db.add(user)
    db.flush()
    return user

async def process_ingestion(db: Session, note_in: NoteCreate, user_uuid: uuid.UUID) -> Note:
    cleaned_content = note_in.content
    loop = asyncio.get_event_loop()
    
    # 1. Clean Text & Extract tags (offloaded)
    extracted_tag_strings = await loop.run_in_executor(None, extract_tags, cleaned_content)
    
    # Process Tags in Postgres
    tag_objects = []
    for t_name in extracted_tag_strings:
        tag = db.query(Tag).filter(Tag.name == t_name).first()
        if not tag:
            tag = Tag(name=t_name)
            db.add(tag)
        tag_objects.append(tag)
    
    # 2. Add to DB
    _ensure_user(db, user_uuid)
    
    db_note = Note(
        user_id=user_uuid,
        content=cleaned_content,
        summary="", # To be generated by LLM later
        source_type=note_in.source_type,
        metadata_json=note_in.metadata_json,
        tags=tag_objects
    )
    db.add(db_note)
    db.commit()
    db.refresh(db_note)
    
    # 3. Create Vector Embedding & Save to VectorDB (offloaded)
    vector = await loop.run_in_executor(None, create_embedding, cleaned_content)
    
    chroma = get_chroma()
    collection = chroma.get_or_create_collection(name="notes_collection")
    collection.add(
        ids=[str(db_note.id)],
        embeddings=[vector],
        documents=[cleaned_content],
        metadatas=[{"user_id": str(user_uuid), "source": note_in.source_type}]
    )
    
    return db_note
